
package Options_Falcutatives;

import Monopoly_Sur_Console.Plateau;
import Interface_Principale.Interface_Plateau;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author maxime.mines-ales
 */
public class DebugMode extends javax.swing.JFrame {
    
    Plateau p;
    
    public DebugMode(Plateau p) {
        initComponents();
        setLayout(new BorderLayout());
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.toFront();
        int nb = p.nbJoueur();
        this.p = p;
        
        NOMBRE_joueur.setText("<html><B><font size='+2'>"+Integer.toString(nb)+"</font></B></html>");
        
        affichage_ajout(nb);
        
        
        
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                Interface_Plateau.DebugMode.setEnabled(true);
            }
        });
    }
    
    public void affichage_ajout(int nb){
        for(int i =0; i<nb; i++){
            if(i ==0){
                listejoueurdetail.setText("<html><B>"+p.getListeJoueur().get(0).getNom());
                Cagnotte_detail.setText("<html><B>"+Integer.toString(p.getListeJoueur().get(0).getPorteMonnaie()));
                Id_player_detail.setText("<html><B>"+Integer.toString(p.getListeJoueur().get(0).getId()));
                for(int k = 0;k<39; k++){
                    if(p.getPropPlateau()[k] == p.getListeJoueur().get(0).getId()+1){
                        Listeprop.setText(Listeprop.getText()+ p.getCasePlateau()[k].getNom()+ "<br>");
                    }
                }
            }
            else{
                listejoueurdetail.setText(listejoueurdetail.getText()+"<br>"+ p.getListeJoueur().get(i).getNom());
                Cagnotte_detail.setText(Cagnotte_detail.getText()+"<br>"+Integer.toString(p.getListeJoueur().get(i).getPorteMonnaie()));
                Id_player_detail.setText(Id_player_detail.getText()+"<br>"+Integer.toString(p.getListeJoueur().get(i).getId()));
            }
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nb_joueur = new javax.swing.JLabel();
        NOMBRE_joueur = new javax.swing.JLabel();
        listejoueurdetail = new javax.swing.JLabel();
        Cagnotte = new javax.swing.JLabel();
        Cagnotte_detail = new javax.swing.JLabel();
        Id_player = new javax.swing.JLabel();
        Id_player_detail = new javax.swing.JLabel();
        hack_cagnotte = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        button_reset_pos = new javax.swing.JButton();
        Listeprop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nb_joueur.setText("Nb de joueurs:");

        NOMBRE_joueur.setText("jLabel2");

        listejoueurdetail.setText("jLabel1");

        Cagnotte.setText("Cagnotte");

        Cagnotte_detail.setText("jLabel1");

        Id_player.setText("id");

        Id_player_detail.setText("jLabel1");

        hack_cagnotte.setText("Money hack");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        button_reset_pos.setText("Reset position");
        button_reset_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_reset_posActionPerformed(evt);
            }
        });

        Listeprop.setText("<html><B>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listejoueurdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Nb_joueur, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NOMBRE_joueur, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cagnotte))
                    .addComponent(Cagnotte_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id_player, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Id_player_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hack_cagnotte, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Listeprop, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(button_reset_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nb_joueur)
                            .addComponent(NOMBRE_joueur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cagnotte)
                            .addComponent(Id_player)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(hack_cagnotte)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listejoueurdetail, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(Cagnotte_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Id_player_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(button_reset_pos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(Listeprop, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    //hack button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int arg = p.getListeJoueur().get(0).getPorteMonnaie();
        p.getListeJoueur().get(0).setPorteMonnaie(p.getListeJoueur().get(0).getPorteMonnaie()+arg);
        affichage_ajout((int) p.nbJoueur());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button_reset_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_reset_posActionPerformed
        // TODO add your handling code here:
        //plateau_maxime.setPos_pion1_case(0);
        //plateau_maxime.setX_pos(600);
        //plateau_maxime.setX_pos(600);
        //Plateau_maxime.Debug.setText("<html>" +plateau_maxime.getS4() +"<br/> Case actuelle du joueur 1: <font color = orange><font size='+1'><B>" + plateau_maxime.getPos_pion1_case() +"</B></font></html>");
        //Plateau_maxime.getImage_pion1().setLocation(Plateau_maxime.getX_casedépart(), Plateau_maxime.getY_casedépart());
    }//GEN-LAST:event_button_reset_posActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cagnotte;
    private javax.swing.JLabel Cagnotte_detail;
    private javax.swing.JLabel Id_player;
    private javax.swing.JLabel Id_player_detail;
    private javax.swing.JLabel Listeprop;
    private javax.swing.JLabel NOMBRE_joueur;
    private javax.swing.JLabel Nb_joueur;
    private javax.swing.JButton button_reset_pos;
    private javax.swing.JLabel hack_cagnotte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel listejoueurdetail;
    // End of variables declaration//GEN-END:variables
}
