/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Case;

import Monopoly_Sur_Console.Joueur;
import Cases.Terrain;
import javax.swing.ImageIcon;
import java.lang.String;
import java.awt.event.*;
import Cases.*;
import javax.swing.JLabel;

/**
 *
 * @author belkh
 */
public class Acheter_Prop extends javax.swing.JFrame {

    Terrain t;
    Joueur j;
    
    ImageIcon imagem = new ImageIcon("m_orange.jpg");
    JLabel image_imagem= new JLabel(imagem);
    /**
     * Creates new form Acheter_Prop
     */
    public Acheter_Prop() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
        possesion.setText("Vous possédez n propriété sur ce terrain");
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        possesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prop.setIcon(imagem);
        prop.setSize(image_imagem.getPreferredSize());
        prix.setText("Prix d'une propriété : €");
        portefeuille.setText("Argent Restant : €");
        Clicklistener click = new Clicklistener();
        oui.addActionListener(click);
        non.addActionListener(click);


    }

    /**
     *
     */
    public class Clicklistener implements ActionListener
  {

        /**
         *
         * @param e
         */
        @Override
    public void actionPerformed(ActionEvent e)
    {
      if (e.getSource() == oui)
      {
        Achete ach = new Achete("CETTE MAGNIFIQUE PROPRIETE");
        int c = t.getPrixMaison();
        j.payer(c);
        dispose();
      }

      if (e.getSource() == non)
      {
        dispose();
      }
    }

  }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        oui = new javax.swing.JButton();
        prop = new javax.swing.JLabel();
        non = new javax.swing.JButton();
        possesion = new javax.swing.JLabel();
        prix = new javax.swing.JLabel();
        portefeuille = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setText("ACHETER UNE PROPRIETE ?");

        oui.setText("OUI");
        oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiActionPerformed(evt);
            }
        });

        prop.setText("Voulez-vous acheter une nouvelle propriété pour votre terrain ?");

        non.setText("NON");

        possesion.setText("Vous possédez n propriété sur ce terrain");

        prix.setText("Prix d'une propriété : ...€");

        portefeuille.setText("Argent Restant : ...€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prop, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prix)
                            .addComponent(portefeuille))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oui)
                        .addGap(18, 18, 18)
                        .addComponent(non)
                        .addGap(78, 78, 78))))
            .addComponent(possesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(possesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prop, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(portefeuille))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oui)
                        .addComponent(non)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ouiActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton non;
    private javax.swing.JButton oui;
    private javax.swing.JLabel portefeuille;
    private javax.swing.JLabel possesion;
    private javax.swing.JLabel prix;
    private javax.swing.JLabel prop;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
