/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Case;

import Monopoly_Sur_Console.Joueur;
import Cases.Terrain;
import javax.swing.ImageIcon;
import Cases.*;
import Monopoly_Sur_Console.Plateau;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author belkh
 */
public class Acheter_Terrain extends javax.swing.JFrame {
    Plateau p;
    Terrain t;
    Joueur j;
    Case c;
    ImageIcon imageProp = new ImageIcon("m_orange.jpg");
    JLabel image_imageProp= new JLabel(imageProp);
    /**
     * Creates new form Acheter_Terrain
     * @param p
     * @param j
     */
    public Acheter_Terrain(Plateau p, Joueur j) {
        initComponents();
        this.p =p;
        this.j =j;
        setVisible(true);
        setLayout(new BorderLayout());
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        Case c = p.getCase(j.getPosition());
        this.c = c;
        nom.setText("<html><font color = blue><font size = '+2'><B>" +c.getNom());
        question.setIcon(imageProp);
        nom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prix.setText("<html>Prix du terrain : "+"<font color = blue ><font size = '+1'><B>"+ c.getPrix()+"€</B></font><html>");
        bourse.setText("<html>Argent Restant : "+"<font color = blue ><font size = '+1'><B>"+j.getPorteMonnaie()+"€</B></font><html>");
        Clicklistener click = new Clicklistener();
        oui.addActionListener(click);
        non.addActionListener(click);
        image_imageProp.setSize(image_imageProp.getPreferredSize());
    }

    /**
     *
     */
    public class Clicklistener implements ActionListener
  {

        /**
         *
         * @param e
         */
        @Override
    public void actionPerformed(ActionEvent e)
    {
      if (e.getSource() == oui)
      {
        Achete ach = new Achete("ce terrain");
        c.acheter(j, p);
        dispose();
      }

      if (e.getSource() == non)
      {
        dispose();
      }
    }

  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        oui = new javax.swing.JButton();
        non = new javax.swing.JButton();
        prix = new javax.swing.JLabel();
        bourse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question.setText("   Voulez-vous acheter ce terrain ?");

        nom.setText("                                                       NOM TERRAIN");

        oui.setText("OUI");
        oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiActionPerformed(evt);
            }
        });

        non.setText("NON");

        prix.setText("Prix du terrain : ...€");

        bourse.setText("Argent Restant : ...€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(bourse, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(oui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(non)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oui)
                    .addComponent(non))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ouiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bourse;
    private javax.swing.JLabel nom;
    private javax.swing.JButton non;
    private javax.swing.JButton oui;
    private javax.swing.JLabel prix;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
