/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Case;

import Monopoly_Sur_Console.Joueur;
import Monopoly_Sur_Console.Plateau;
import java.awt.FontMetrics;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author belkh
 */
public class CC extends javax.swing.JFrame {

    ImageIcon caisse_communaute = new ImageIcon("communaute.jpg");
    Carte_Com c;
    Joueur j;
    Plateau p;
    JLabel image_imagecc= new JLabel(caisse_communaute);
    
    /**
     * Creates new form CC
     * @param c
     */
    public CC(Carte_Com c) {
        initComponents();
        setVisible(true);
        setLayout(new BorderLayout());
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.c = c;
        FontMetrics metrics = texte.getFontMetrics(texte.getFont());
        //On récupère la largeur du message du JLabel
        this.setLocationRelativeTo(null);
        texte.setText(c.getCommentaire());
        st.setText(c.getTitre());
        st.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte.setIcon(caisse_communaute);
        int messageWidth = metrics.stringWidth(texte.getText());
        texte.setSize(600,120); // Hauteur arbitraire de 50
        int messageWidth2 = metrics.stringWidth(st.getText());
        st.setSize(120,50); // Hauteur arbitraire de 50
        image_imagecc.setSize(image_imagecc.getPreferredSize());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        texte = new javax.swing.JLabel();
        st = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setText("CARTE CAISSE DE COMMUNAUTE");

        texte.setText("Modifier selon la carte");

        st.setText("sous-titre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(st, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texte, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel st;
    private javax.swing.JLabel texte;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
