/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Case;

import Monopoly_Sur_Console.Joueur;
import java.lang.String;
import java.awt.event.*;
import Cases.*;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author belkh
 */
public class Compagnie extends javax.swing.JFrame {

    ServicePublic sc;
    Joueur j;
    Case c;
    
    /**
     * Creates new form Acheter_Prop
     * @param c
     * @param j
     */
    public Compagnie(Case c, Joueur j) {
        this.c = c;
        this.j =j;
        
        initComponents();
        setVisible(true);
        setLayout(new BorderLayout());
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        //titre.setText(sc.getNom());
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prix.setText("<html>Prix de la propriété : "+"<font color = pink ><font size = '+1'><B>"+c.getPrix()+"€</B></font><html>");
        bourse.setText("<html>Argent restant au joueur : "+"<font color = pink ><font size = '+1'><B>"+j.getPorteMonnaie()+"€</B></font><html>");
        Clicklistener click = new Clicklistener();
        oui.addActionListener(click);
        non.addActionListener(click);

        
    }

    /**
     *
     */
    public class Clicklistener implements ActionListener
  {

        /**
         *
         * @param e
         */
        @Override
    public void actionPerformed(ActionEvent e)
    {
      if (e.getSource() == oui)
      {
        Achete ach = new Achete("CETTE MAGNIFIQUE COMPAGNIE");
        int c = sc.getPrix();
        j.payer(c);
        dispose();
      }

      if (e.getSource() == non)
      {
        dispose();
      }
    }

  }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        titre = new javax.swing.JLabel();
        texte = new javax.swing.JLabel();
        prix = new javax.swing.JLabel();
        bourse = new javax.swing.JLabel();
        oui = new javax.swing.JButton();
        non = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setText("COMPAGNIE DE DISTRIBUTION");

        texte.setText("Voulez-vous aquérir cette compagnie de distribution ?");

        prix.setText("Prix de la compagnie : ...€");

        bourse.setText("Argent Restant : ...€");

        oui.setText("OUI");

        non.setText("NON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prix, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(bourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(oui)
                .addGap(26, 26, 26)
                .addComponent(non)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texte, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(texte, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oui)
                            .addComponent(non))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bourse, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bourse;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton non;
    private javax.swing.JButton oui;
    private javax.swing.JLabel prix;
    private javax.swing.JLabel texte;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
