/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Case;

import Cases.Terrain;
import Monopoly_Sur_Console.Joueur;
import Monopoly_Sur_Console.Plateau;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author belkh
 */
public class Payer_Loyer extends javax.swing.JFrame {

    ImageIcon imagem = new ImageIcon("monop.jpg");
    Joueur j;
    Terrain t;
    Plateau p;
    JLabel image_imagem= new JLabel(imagem);
    
    /**
     * Creates new form Payer_Loyer
     * @param j
     * @param p
     */
    public Payer_Loyer(Joueur j, Plateau p) {
        this.j =j;
        this.p = p;
        initComponents();
        this.setLocationRelativeTo(null);
        image.setIcon(imagem);
        explication.setText("Le Joueur "+j.getNom()+" possède le terrain "+p.getCase(j.getPosition()).getNom()+", et "+ p.getCase(j.getPosition()).getMaison()+" propriétés y sont plaçées");
        explication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        image_imagem.setSize(image_imagem.getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        explication = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titre.setText("PAYEZ VOTRE LOYER !");

        explication.setText("Le Joueur n°... possède le terrain n°... et n propriété");

        image.setText("Vous lui devez ... €");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(image)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(titre))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(explication))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titre)
                .addGap(18, 18, 18)
                .addComponent(explication)
                .addGap(42, 42, 42)
                .addComponent(image)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel explication;
    private javax.swing.JLabel image;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
